"""Create user table

Revision ID: 0fe5e73d9c75
Revises: fe76607c18e3
Create Date: 2024-09-15 01:25:19.620472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe5e73d9c75'
down_revision = 'fe76607c18e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wechat_unionid', sa.String(length=63), nullable=True, comment='微信UnionID'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('wechat_unionid')

    # ### end Alembic commands ###
