"""Add User model with schema

Revision ID: 1c489f38bf93
Revises: 
Create Date: 2024-09-15 00:50:35.234626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c489f38bf93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False, comment='用户唯一ID，UUID'),
    sa.Column('username', mysql.VARCHAR(length=63), nullable=True, comment='用户名'),
    sa.Column('phone_number', mysql.VARCHAR(length=63), nullable=True, comment='电话号码'),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True, comment='电子邮件地址'),
    sa.Column('wechat_openid', mysql.VARCHAR(length=63), nullable=True, comment='微信OpenID'),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True, comment='密码'),
    sa.Column('session_key', mysql.VARCHAR(length=127), nullable=True, comment='微信登录加密密钥'),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
