"""更改活动数据模型

Revision ID: 39e549fddf38
Revises: d6692a478cde
Create Date: 2024-09-15 18:39:53.791678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e549fddf38'
down_revision = 'd6692a478cde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True, comment='活动是否发布/公开'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
