"""添加基础模型，每个模型加入创建时间和最新更改时间的字段

Revision ID: 5e456b7ac8e8
Revises: eb7fae74cdb7
Create Date: 2024-09-17 00:05:45.677473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e456b7ac8e8'
down_revision = 'eb7fae74cdb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户ID'),
    sa.Column('balance', sa.Integer(), nullable=False, comment='当前积分余额'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='记录更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('points_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户ID'),
    sa.Column('change_amount', sa.Integer(), nullable=False, comment='积分变化数'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='交易描述'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='交易创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='记录更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户ID'),
    sa.Column('balance', sa.Float(), nullable=False, comment='钱包余额'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='记录创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='记录更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户ID'),
    sa.Column('amount', sa.Float(), nullable=False, comment='交易金额'),
    sa.Column('transaction_type', sa.String(length=50), nullable=True, comment='交易类型，如充值、消费'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='交易描述'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='交易创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='记录更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, comment='记录创建时间'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, comment='记录更新时间'))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, comment='记录创建时间'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, comment='记录更新时间'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False, comment='记录创建时间'))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, comment='记录更新时间'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    op.drop_table('wallet_transaction')
    op.drop_table('wallet')
    op.drop_table('points_transaction')
    op.drop_table('points')
    # ### end Alembic commands ###
