"""Add Event model

Revision ID: d6692a478cde
Revises: 1f9938390d24
Create Date: 2024-09-15 15:49:44.102022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6692a478cde'
down_revision = '1f9938390d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False, comment='活动唯一ID，UUID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='活动名称'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='活动开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=False, comment='活动结束时间'),
    sa.Column('registration_start_time', sa.DateTime(), nullable=True, comment='报名开始时间'),
    sa.Column('registration_end_time', sa.DateTime(), nullable=True, comment='报名结束时间'),
    sa.Column('max_participants', sa.Integer(), nullable=False, comment='最大报名人数'),
    sa.Column('organizers', sa.Text(), nullable=True, comment='活动主办单位'),
    sa.Column('co_organizers', sa.Text(), nullable=True, comment='活动承办单位'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='活动地点'),
    sa.Column('details', sa.Text(), nullable=True, comment='活动详情（Markdown 格式）'),
    sa.Column('images', sa.Text(), nullable=True, comment='活动图片海报（URL 列表）'),
    sa.Column('registration_review_required', sa.Boolean(), nullable=True, comment='报名是否需要审核'),
    sa.Column('registration_required', sa.Boolean(), nullable=True, comment='活动是否需要报名'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.String(length=36), nullable=False, comment='联系人唯一ID，UUID'),
    sa.Column('event_id', sa.String(length=36), nullable=False, comment='活动ID，外键'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='联系人姓名'),
    sa.Column('channel', sa.String(length=50), nullable=False, comment='联系方式渠道（电话、微信、邮箱等）'),
    sa.Column('value', sa.String(length=255), nullable=False, comment='联系方式的值'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contacts')
    op.drop_table('events')
    # ### end Alembic commands ###
