"""Change Event model

Revision ID: eb7fae74cdb7
Revises: 02e2953481e2
Create Date: 2024-09-16 02:06:23.529142

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb7fae74cdb7'
down_revision = '02e2953481e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_delete', sa.Boolean(), nullable=False, comment='活动是否归档、删除'))
        batch_op.alter_column('is_public',
               existing_type=mysql.TINYINT(display_width=1),
               comment='活动是否发布、公开',
               existing_comment='活动是否发布/公开',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('is_public',
               existing_type=mysql.TINYINT(display_width=1),
               comment='活动是否发布/公开',
               existing_comment='活动是否发布、公开',
               existing_nullable=False)
        batch_op.drop_column('is_delete')

    # ### end Alembic commands ###
