"""Create user table

Revision ID: fe76607c18e3
Revises: 1c489f38bf93
Create Date: 2024-09-15 01:08:11.185104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe76607c18e3'
down_revision = '1c489f38bf93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='用户唯一ID，UUID'),
    sa.Column('username', sa.String(length=63), nullable=True, comment='用户名'),
    sa.Column('phone_number', sa.String(length=63), nullable=True, comment='电话号码'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='电子邮件地址'),
    sa.Column('wechat_openid', sa.String(length=63), nullable=True, comment='微信OpenID'),
    sa.Column('password', sa.String(length=255), nullable=True, comment='密码'),
    sa.Column('session_key', sa.String(length=127), nullable=True, comment='微信登录加密密钥'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
