name: Build and Push to Aliyun Docker Registry

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # 设置 Python 版本为 3.11
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 登录到阿里云 Docker Registry
    - name: Log in to Aliyun Docker Registry
      uses: docker/login-action@v3
      with:
#        registry: registry.cn-shanghai.aliyuncs.com
        registry: ${{ secrets.ALIYUN_REGISTRY }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}

    # 构建 Docker 镜像
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACE }}/finolab:latest .

    # 推送 Docker 镜像到阿里云 Docker Registry
    - name: Push Docker image
      run: |
        docker push ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAMESPACE }}/finolab:latest
