name: Build and Push to Tencent Cloud Docker Registry

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # 设置 Python 版本为 3.11
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 登录到腾讯云 Docker Registry
    - name: Log in to Tencent Cloud Docker Registry
      uses: docker/login-action@v3
      with:
        # registry: ccr.ccs.tencentyun.com
        registry: ${{ secrets.TCR_REGISTRY }}
        username: ${{ secrets.TCR_USERNAME }}
        password: ${{ secrets.TCR_PASSWORD }}

    # 构建 Docker 镜像
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.TCR_REGISTRY }}/${{ secrets.TCR_NAMESPACE }}/finolab:latest .

    # 推送 Docker 镜像到腾讯云 Docker Registry
    - name: Push Docker image
      run: |
        docker push ${{ secrets.TCR_REGISTRY }}/${{ secrets.TCR_NAMESPACE }}/finolab:latest

